### ISSUE TITLE
How do I start this container?

### ISSUE THREAD

**Issue by mikeder** [mcansky/cabotapp#3]
First time trying out Docker and Cabot, and could use some help starting this container. I have tried both your build and my own build with the same result.

When I run:

```
sudo docker run --name cabot1 --env-file ./cabot1env mcansky/cabot 
```

I just get dumped at a Python 2.7 terminal. How do I get this container to run while passing in the variables via an env file?

**Comment by mcansky** [comment]
wow, a year ago, truly sorry I haven't spotted that; did you sort your issue since then ?

**Comment by mikeder** [comment]
Yea I eventually figured it out, thanks :+1:
